package com.gnacoding.composecalculator.ui.theme

import androidx.compose.ui.graphics.Color



val md_theme_light_primary = Color(0xFF6d4ea2)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFecdcff)
val md_theme_light_onPrimaryContainer = Color(0xFF260059)
val md_theme_light_secondary = Color(0xFF635a70)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFeadef7)
val md_theme_light_onSecondaryContainer = Color(0xFF1f182b)
val md_theme_light_tertiary = Color(0xFF7f525d)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffd9e1)
val md_theme_light_onTertiaryContainer = Color(0xFF32101a)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfffbfc)
val md_theme_light_onBackground = Color(0xFF1d1b1e)
val md_theme_light_surface = Color(0xFFfffbfc)
val md_theme_light_onSurface = Color(0xFF1d1b1e)
val md_theme_light_surfaceVariant = Color(0xFFe8e0eb)
val md_theme_light_onSurfaceVariant = Color(0xFF49454e)
val md_theme_light_outline = Color(0xFF7a757e)
val md_theme_light_inverseOnSurface = Color(0xFFf5eff4)
val md_theme_light_inverseSurface = Color(0xFF323033)
val md_theme_light_inversePrimary = Color(0xFFd5baff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFd5baff)
val md_theme_dark_onPrimary = Color(0xFF3d1c70)
val md_theme_dark_primaryContainer = Color(0xFF543588)
val md_theme_dark_onPrimaryContainer = Color(0xFFecdcff)
val md_theme_dark_secondary = Color(0xFFcec2db)
val md_theme_dark_onSecondary = Color(0xFF342d40)
val md_theme_dark_secondaryContainer = Color(0xFF4b4358)
val md_theme_dark_onSecondaryContainer = Color(0xFFeadef7)
val md_theme_dark_tertiary = Color(0xFFf1b7c4)
val md_theme_dark_onTertiary = Color(0xFF4a252f)
val md_theme_dark_tertiaryContainer = Color(0xFF643a45)
val md_theme_dark_onTertiaryContainer = Color(0xFFffd9e1)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1d1b1e)
val md_theme_dark_onBackground = Color(0xFFe7e1e6)
val md_theme_dark_surface = Color(0xFF1d1b1e)
val md_theme_dark_onSurface = Color(0xFFe7e1e6)
val md_theme_dark_surfaceVariant = Color(0xFF49454e)
val md_theme_dark_onSurfaceVariant = Color(0xFFcbc4cf)
val md_theme_dark_outline = Color(0xFF958f99)
val md_theme_dark_inverseOnSurface = Color(0xFF1d1b1e)
val md_theme_dark_inverseSurface = Color(0xFFe7e1e6)
val md_theme_dark_inversePrimary = Color(0xFF6d4ea2)
val md_theme_dark_shadow = Color(0xFF000000)

val iconPurple = Color(0xFF563e80)
val iconBlue = Color(0xFF19989e)